### PR TITLE
EbPhotoSite: French strings courtesy of Google Translate

### PR DESCRIPTION
**Pull request by tpaik18**
Generated a fr.json for EbPhotoSite in order to test https://auderenow.atlassian.net/browse/FEV-1074

image

### CODE REVIEW

**Comment by tpaik18** [comment]
Okay, the French site doesn't look like it has any glaring errors now based on my mediocre French. @auderephilip not sure if merging this in might have any possible demo value?

**Comment by tpaik18** [comment]
Great work done by @Ninjestic to pull all the strings out. 
@auderephilip Merged. To see the site in French, change Chrome settings > Advanced > Language to add/set French the top language, then reload the page. If we don't demo this in the near future though, I would vote to take fr.json out because keeping strings in sync is such a pain.

**Comment by auderephilip** [comment]
Ah, good to know.  Thanks for the extra context, @tpaik18.  Would it be workable to let the strings drift for now (if divergence happens) and for us to update them one more time if we get a big demo in the future?  It'd be ideal if we could minimize the number of times we need to keep strings in sync... (or if it's not easy/possible to batch up the updates to minimize that cost, LMK...)

**Comment by tpaik18** [comment]
@auderephilip Okay yes that would work too.

**Pull request merged**
